name: Fetch and Publish Security News

on:
  schedule:
    - cron: "0 */8 * * *"  # every 8 hours
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          CONVEX_API_KEY: ${{ secrets.CONVEX_API_KEY }}
        run: |
          python get_news.py

      - name: Set up GitHub token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news_data/
          git commit -m "Update news CSVs [skip ci]" || echo "No changes"
          git push
